variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CI_REGISTRY: https://index.docker.io/v1/
  CI_REGISTRY_IMAGE: pseipp/taxipp-life-dependance-ci

cache:
  paths:
    - .cache/pip
    - ./figures/

stages:
  - docker
  - build


build Docker image:
  stage: docker
  when: manual
  tags:
    - openfisca
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    # From https://github.com/GoogleContainerTools/kaniko#pushing-to-docker-hub
    - DOCKER_HUB_AUTH=$(echo -n $DOCKER_HUB_USER:$DOCKER_HUB_PASSWORD | base64)
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$DOCKER_HUB_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.ci --destination $CI_REGISTRY_IMAGE:latest


build collections:
  stage: build
  image: $CI_REGISTRY_IMAGE:latest
  tags:
    - openfisca
  before_script:
    - pip install -e .[dev]
    - mkdir -p ~/.config/openfisca-survey-manager
    - cp ./runner/openfisca_survey_manager_raw_data.ini ~/.config/openfisca-survey-manager/raw_data.ini
    - cp ./runner/openfisca_survey_manager_config.ini ~/.config/openfisca-survey-manager/config.ini
    - mkdir -p /root/ci-files/data_collections
    - pip3 install -e .[dev,survey]

  script:
    - build-collection -c enquete_logement -d -m -s 2013
    - build-collection -c erfs_fpr -d -m -s 2013
    - cp ~/.config/openfisca-survey-manager/config.ini  /home/ipp/data/openfisca-france-data/openfisca_survey_manager_config.ini
  when: manual

Build input data:
  stage: build
  image: $CI_REGISTRY_IMAGE:latest
  tags:
    - openfisca
  before_script:
    - mkdir -p ~/.config/openfisca-survey-manager
    - pip3 install -e .[dev,survey]
    - cp ./runner/openfisca_survey_manager_raw_data.ini ~/.config/openfisca-survey-manager/raw_data.ini
    - cp /home/ipp/data/openfisca-france-indirect-taxation/openfisca_survey_manager_config.ini ~/.config/openfisca-survey-manager/config.ini
    - mkdir -p /root/ci-files/data_collections
  script:
    - build-erfs-fpr -y 2013
    - cp ~/.config/openfisca-survey-manager/config.ini /home/ipp/data/openfisca-france-indirect-taxation/openfisca_survey_manager_config_with_mathed_data.ini
  when: manual