###############################################################################
## File for Anaconda.org
## It use Jinja2 templating code to retreive information from setup.py
###############################################################################

{% set name = "openfisca-france-data" %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    {% for req in data.get('install_requires', []) %}
    - {{ req }}
    {% endfor %}

test:
  imports:
    - openfisca_france_data
  requires:
    - pip
  commands:
    #- pip check # TODO: openfisca-core 35.7.6 requires pytest, which is not installed. !!!
    - pip list

outputs:
  - name: openfisca-france-data

  - name: openfisca-france-data-test
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        {% for req in data.get('extras_require', []) %}
        - {{ req }}
        {% endfor %}
        - {{ pin_subpackage('openfisca-france-data', exact=True) }}

about:
  home: https://fr.openfisca.org/
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: "OpenFisca-France-Data module to work with French survey data"
  description: |
    OpenFisca is a versatile microsimulation free software.
    This repository contains the module to work with French survey data.
  doc_url: https://fr.openfisca.org/
  dev_url: https://github.com/openfisca/openfisca-france-data/
