# Template du fichier raw_data.ini de openfisca-survey-manager
# pour qu'il fonctionne avec oepnfisca-france-data
# sur le runner gitlab piloté par ipp/openfisca-france/data

; [enquete_logement]
; 2006 = /home/ipp/data/enquete_logement/2006/stata
; 2013 = /home/ipp/data/enquete_logement/2013/stata

[erfs_fpr]
2012 = /mnt/data-in/erfs-fpr/2012/stata
2013 = /mnt/data-in/erfs-fpr/2013/stata
2014 = /mnt/data-in/erfs-fpr/2014/sas
2015 = /mnt/data-in/erfs-fpr/2015/csv
2016 = /mnt/data-in/erfs-fpr/2016/sas
2017 = /mnt/data-in/erfs-fpr/2017/csv
2018 = /mnt/data-in/erfs-fpr/2018/sas
